micronaut:
  application:
    name: mnQuickstart
  server:
    port: ${SERVER_PORT:8081}
netty:
  default:
    allocator:
      max-order: 3
hello:
  world:
    message: "Hello from application.yaml"
    translation:
      sq: "Pershendetje"
      de: "Hello Welt"


